Added user friendly labels to teaser modules
CONTENIDO/CONTENIDO pull request #202
Opened 2021-08-23 14:44 UTC by tone2tone

Similar to all other content type modules, teaser modules CAN be equipped with smarty functionality, in this instance to produce nothing more than the appropriate label. I changed all three teaser modules, swapped code lines and added smarty support. 
As well, I changed the teaser class to change the order of what is displayed when. The img button that produces the settings popup for teasers now moved on TOP of the frontend output, instead of being on BOTTOM as was before. The order of display is now: 
- label
- icon button to open settings
- frontend output
Module language translations have been updated with label suggestions. 
With this update, administrators have further control over labels. Design and behaviour have to be addressed in CSS and are not subject to this feature update.

2021-08-24 11:31 UTC, purcaholic approved these changes, later dismissed
Please use only Smarty in module outputs.

2021-08-24 11:31 UTC, purcaholic commented on setup/data/examples/data/modules/content_teaser_image/php/content_teaser_image_output.php
>  mi18n("MORE");
Please don't mix regular output with Smarty, this not a good idea. Since we are already startet using Smarty, then everything should be ported to Smarty.

2021-08-24 11:31 UTC, purcaholic commented on setup/data/examples/data/modules/content_teaser_slider/php/content_teaser_slider_output.php
>  mi18n("MORE");
See comment above in content_teaser_image_output.php.

2021-08-24 11:31 UTC, purcaholic commented on setup/data/examples/data/modules/content_teaser_text/php/content_teaser_text_output.php
>  mi18n("MORE");
See comment above in content_teaser_image_output.php.

2021-08-24 11:32 UTC, purcaholic requested changes
Please use Smarty in module outputs.

2021-08-24 13:13 UTC, tone2tone commented on setup/data/examples/data/modules/content_teaser_image/php/content_teaser_image_output.php
>  mi18n("MORE");
We can't, sorry. In this instance, pushingthe CSM_TEASER into a variable and assign it to samrty results in smashed teaser output. The only way right now to keep everything in order is to echo the teaser as shown. I tried lots of stuff to use smarty here, but wasn't successful.

2021-08-24 16:19 UTC, purcaholic commented on setup/data/examples/data/modules/content_teaser_image/php/content_teaser_image_output.php
>  mi18n("MORE");
@tone2tone The value of "CMS_TEASER[2]"; is PHP code, which is interpreted immadiately.

Following code should work:
```
<?php

/**
 * description: standard teaser - image teaser
 *
 * @package Module
 * @subpackage ContentTeaserImage
 * @author timo.trautmann@4fb.de
 * @copyright four for business AG <www.4fb.de>
 * @license http://www.contenido.org/license/LIZENZ.txt
 * @link http://www.4fb.de
 * @link http://www.contenido.org
 */

// Get teaser output
ob_start();
"CMS_TEASER[2]";
$teaser = ob_get_contents();
ob_end_clean();

// Output mode
$tpl = cSmartyFrontend::getInstance();
$tpl->assign('backend', cRegistry::isBackendEditMode());
$tpl->assign('label', mi18n("LABEL_TEXT"));
$tpl->assign('teaser', $teaser);
$tpl->display('get.tpl');

?>
```

And then in the template ´get.tpl´:
```
{if $backend}
    <label class="content_type_label teaser_icon">{$label|escape}</label>
{/if}
{$teaser}
```

2021-08-24 21:26 UTC, tone2tone commented on setup/data/examples/data/modules/content_teaser_image/php/content_teaser_image_output.php
>  mi18n("MORE");
Nope, sorry, won't work - with your version, the backend image button to edit the teaser is not visible; only if I add "echo" before calling the teaser:

```
// Get teaser output
ob_start();
"CMS_TEASER[2]";
$teaser = ob_get_contents();
ob_end_clean(); 
```
This way, I AM able to incorporate the teaser in Smarty. Shall I do so?

2021-08-24 22:22 UTC, purcaholic commented on setup/data/examples/data/modules/content_teaser_image/php/content_teaser_image_output.php
>  mi18n("MORE");
@tone2tone yes, do the change with your fix please.

2021-08-25 07:32 UTC, tone2tone commented on setup/data/examples/data/modules/content_teaser_image/php/content_teaser_image_output.php
>  mi18n("MORE");
@purcaholic Sorry Murat, as a newbee with GIT I struggled to understand how to undo a commit and rebase and stuff and might have produced unnecessary commits. Can you live with what is online now?

2021-08-25 20:24 UTC, muratpurc approved these changes

2021-08-25 20:24 UTC, muratpurc commented on setup/data/examples/data/modules/content_teaser_slider/php/content_teaser_slider_output.php
>  mi18n("MORE");
@tone2tone you could have removed the lines `mi18n("MORE");` from the module outputs, since they are needless, but the rest is o.k.. Thank you.

2021-08-25 20:24 UTC, merged

2021-08-25 20:38 UTC, tone2tone commented
@purcaholic well, I didn't delete the MORE-translation thing as it really influenced the frontend display of said string... when I changed the German translation in the module from "weiterlesen" to "weiterlesen2", it was displayed this way in the frontend teaser box. It seems that this is a way of making the translation flexible (at least for frontend purposes?).