Added class and function to new central "date checking" routine
CONTENIDO/CONTENIDO pull request #203
Opened 2021-08-23 19:29 UTC by tone2tone

A new validator class is there to check dates; functions.general.php have been updated to serve new functions.
The class function isValidDate($date) will allow for $date being Y-m-d format as well as Y-m-d H:i:s to return true or false. 
Zero based values "0000-00-00" and such: false
Non-existing dates: false
NULL: false
Empty String: false

2021-08-24 11:39 UTC, purcaholic requested changes
Please implement a unit test for the new validator. We should try to cover new features with unit tests. This is not always easy to achive, but it should be not a problem in this case. See `cValidatorEmailTest` which tests the `cValidatorEmail` class.

2021-08-24 13:21 UTC, tone2tone commented
@purcaholic Sorry to say I do not have a clue how to adapt cValidatorEmailTest to the needs of this date thing. I have never worked with unit test and do not understand what all the functions are there for or do ... I can only say I tested it with a module, checking various inputs to the function and had the outcome mentioned above.

2021-08-25 12:30 UTC, tone2tone commented
I have setup a new file cValidatorDateTest.php and I think I understood how to configure it BUT I do not see how to include it somewhere to use it for checks and how the output is done. In a module? How? I find no comparable code for emailValidation that I could use to check it for dates now.

2021-08-25 21:58 UTC, muratpurc commented
@tone2tone Your IDE should support running unit tests, you may need to install a plugin to run PHPUnit.

But you need some preparation beforehand.

1. Install composer on your development environment
2. Run `composer update` command within your project root folder (the folder which contains the composer.json file), this will install PHPUnit
3. Install or configure PHPUnit in your IDE 

You can alternatively run (within project root folder) a test for a specific file as follows:
`./vendor/bin/phpunit {path_to_the_file_without_ext}`
Example:
`./vendor/bin/phpunit ./test/contenido/validator/cValidatorEmailTest`

2021-08-25 23:01 UTC, tone2tone commented
@purcaholic Sorry to say Murat, but to me - as of now - this is far too complicated to make it work on my machine with just basic knowledge of VS, plugins and stand-alone Software that has to work together, not knowing what I will HAVE to see IF it's running fine. Can't waste that time right now to make it work, sorry. 
I can only offer the information how I came to the conclusion above on WHEN the function returns true or false by posting the code I put into a module to check it manually.
```
if (isValidDate("0000-00-00 00:00:00")) {
    // returns false
	
	print "0000-00-00 00:00:00 is true";
} else {

	print "0000-00-00 00:00:00 is false";
}
	
if (isValidDate("2021-10-08 00:00:00")) {
    // true
	
	print "2021-10-08 00:00:00 is true";
} else {

	print "2021-10-08 00:00:00 is false";
}

if (isValidDate("2021-10-08")) {
    // true
	
	print "2021-10-08 is true";
} else {

	print "2021-10-08 is false";
}

if (isValidDate("2021-13-08")) {
    // false
	
	print "2021-13-08 is true";
} else {

	print "2021-13-08 is false";
}
if (isValidDate(NULL)) {
    // false
	
	print "NULL is true";
} else {

	print "NULL is false";
}		

if (isValidDate("")) {
    // false
	
	print "empty is true";
} else {

	print "empty is false";
}
```

2021-08-26 22:19 UTC, muratpurc commented on contenido/classes/validator/class.validator.date.php
> +        $d = DateTime::createFromFormat($format, $date);
Validdator should set an error, if the validation fails. See `cValidatorEmail` or `cValidatorRegex`.

Following line should be enough in case the passed value is not a proper date.
`$this->addError('Invalid date', 1);
`

2021-08-26 22:24 UTC, muratpurc commented
It is ok, you don't need to deal with unit tests. I'll create a new ticket for it.

But the code in `cValidatorDate` requires some improvement, see my comment:
https://github.com/CONTENIDO/CONTENIDO/pull/203#pullrequestreview-739983275

2021-08-27 07:34 UTC, tone2tone commented
@purcaholic I have created a file already, I am just not able to test it. If you can do that, everything's fine. 
File: cValidatorDateTest.php
content:

```
<?php

/**
 * This file contains tests for the mail validator.
 *
 * @package    Testing
 * @subpackage Test_Validator
 * @author     Viktor Lehmann <info@tone2tone.com>
 * @copyright  four for business AG <www.4fb.de>
 * @license    http://www.contenido.org/license/LIZENZ.txt
 * @link       http://www.4fb.de
 * @link       http://www.contenido.org
 */

/**
 * Class to test date validator.
 *
 * Most of the code below s taken over from
 * http://code.google.com/p/php-email-address-validation/
 *
 * @package    Testing
 * @subpackage Test_Validator
 */
class cValidatorDateTest extends cTestingTestCase
{
    /**
     *
     * @var cValidatorAbstract
     */
    protected $_validator = null;

    /**
     * @throws cInvalidArgumentException
     */
    protected function setUp(): void
    {
        global $cfg;

        $cfg['validator']['date'] = [];

        $this->_validator = cValidatorFactory::getInstance('date');
    }

    /**
     *
     */
    protected function tearDown(): void
    {
        global $cfg;
        unset($this->_validator, $cfg['validator']['date']);
    }

    public function dataIsValid()
    {
        return [
            'Null'  => [null, false],
            'Empty' => ['', false],
            'No real year'   => ['8021-12-08', false],
            'No real month' => ['2021-13-08', false],
            'No real day'  => ['2021-02-31', false],
            'String in no date format'  => ['foobar', false],
            'Existing date without time'  => ['2021-08-21', true],
            'Existing date with time'  => ['2021-08-21 12:21:34', true],
            'Existing date with wrong time'  => ['2021-08-21 12:78:34', false],
        ];
    }

    /**
     * @dataProvider dataIsValid()
     *
     * @param string $input
     * @param bool $output
     */
    public function testIsValid($input, $output)
    {
        $this->assertEquals($output, $this->_validator->isValid($input));
    }
}

```

2021-08-27 08:25 UTC, tone2tone commented
@purcaholic Updated the class accordingly with separate checks and returns and tested it against my module checks which are still fine and correct.

2021-08-28 06:26 UTC, merged