#208 Detect and log missing plugins that are activated in database table
CONTENIDO/CONTENIDO pull request #217
Opened 2021-08-29 21:10 UTC by tone2tone

Problem summary: when swapping contenido folders (e.g. in case of an update/upgrade), it might happen that previously (and still) activated plugins are physically not yet present in the new contenido folder. If so, this causes multiple problems at unexpected places. Some backend menus won't work or don't show their content pages. 
This extended plugin check routine logs error messages if a) a plugin folder for an activated plugin is not there and b) the folder is there, but config.plugin.php is not available, for whatever reason.

2021-08-29 21:21 UTC, purcaholic requested changes

2021-08-29 21:21 UTC, purcaholic commented on contenido/includes/functions.includePluginConf.php
> +        cWarning(__FILE__, __LINE__, "Plugin <" . $pluginName. "> is activated in database, but folder does not exist. This leads to errors e.g. in user or group rights area settings.");
Please indent body of else condition.

2021-08-29 21:21 UTC, purcaholic commented on contenido/includes/functions.includePluginConf.php
> +	}
Please use whitespaces, not tab.

2021-08-30 08:17 UTC, tone2tone commented on contenido/includes/functions.includePluginConf.php
> +	}
done! New commit uploaded.

2021-08-30 09:13 UTC, merged

2023-01-18 08:19 UTC, gonatan commented
@purcaholic This merged PR is still "In progress" on the Kanban board.
It's probably because you still "request changes". Can you accept these?
I guess the board entry will then move to "Done".